LANG = {
	en : {
		all : 'All',
		contact : 'Contact',
		email : 'Email',
		hireMe : 'Hire me',
		hiringOver : 'You have an awesome idea? Let\'s make it happen!',
		freeSoftware : 'Free software',
		message : 'Message',
		messageSent : 'Your message has been successfully sent!',
		myRole : 'My role',
		name : 'Name',
		language : 'Language',
		projects : 'Projects',
		projectsOver : 'Check out some of the projects I\'ve been working on',
		send : 'Send',
		sending : 'Sending',
		subject : 'Subject',
		thisSiteIs : 'This site is'
	},
	es : {
		all : 'Todo',
		contact : 'Contacto',
		email : 'Email',
		hireMe : 'Contrátame',
		hiringOver : '¿Tienes una idea genial? !Hagámosla realidad!',
		freeSoftware : 'Software libre',
		message : 'Mensaje',
		messageSent : '¡Tu mensaje se ha enviado correctamente!',
		myRole : 'Mi rol',
		name : 'Nombre',
		language : 'Idioma',
		projects : 'Proyectos',
		projectsOver : 'Echa un vistazo a algunos de los proyectos en los que he estado trabajando',
		subject : 'Asunto',
		send : 'Enviar',
		sending : 'Enviando',
		thisSiteIs : 'Este site es'
	}
};
